
/* PATHs to test files */
#define FMU1_DLL_ME_PATH @FMU1_DLL_ME_PATH@ 
#define FMU1_DLL_CS_PATH @FMU1_DLL_CS_PATH@
#define COMPRESS_DUMMY_FILE_PATH_SRC "@COMPRESS_DUMMY_FILE_PATH_SRC@"
#define COMPRESS_DUMMY_FILE_PATH_DIST "@COMPRESS_DUMMY_FILE_PATH_DIST@"
#define UNCOMPRESSED_DUMMY_FILE_PATH_SRC "@UNCOMPRESSED_DUMMY_FILE_PATH_SRC@"
#define UNCOMPRESSED_DUMMY_FOLDER_PATH_DIST "@UNCOMPRESSED_DUMMY_FOLDER_PATH_DIST@"

#define CTEST_RETURN_SUCCESS @CTEST_RETURN_SUCCESS@
#define CTEST_RETURN_FAIL @CTEST_RETURN_FAIL@

#define FMU_DUMMY_ME_MODEL_IDENTIFIER @FMU_DUMMY_ME_MODEL_IDENTIFIER@
#define FMU_DUMMY_CS_MODEL_IDENTIFIER @FMU_DUMMY_CS_MODEL_IDENTIFIER@


