FROM fmil_ubuntu16:latest

# Copied this from P500, because I think Jenkins can't clean up properly
# otherwise:
# Add jenkins owner and run as jenkins
RUN groupadd -g 999 jenkins && \
    useradd -r -u 999 -g jenkins jenkins

WORKDIR /fmil/project

COPY . .

